### ISSUE TITLE
Deadline FOSDEM 2016

### ISSUE THREAD

**Issue by j-rivero** [fosdem-testingautomation/fosdem-testingautomation.github.io#7]
Hi:

Excuse me if this is not the best place for asking questions, I could not find a better one. Quick question:

The CFP deadline in [the official web](http://fosdem-testingautomation.github.io/) shows two different dates: 30th Nov (same than this repository) and 10th Dec (probably a manual modification).

Which one is the good one? 
Thanks.

**Comment by rtyler** [comment]
Sorry, this was my mistake
