### ISSUE TITLE
No schedule announced

### ISSUE THREAD

**Issue by MalteSchledjewski** [fosdem-testingautomation/fosdem-testingautomation.github.io#8]
The page states "Schedule Announced: 15 December 2015" but
https://fosdem.org/2016/schedule/track/testing_and_automation/ is empty.

**Comment by rtyler** [comment]
Known issue, we're wrapping the reviewing period up. Unsurprisingly, everybody is busy around the holidays :)

**Comment by rtyler** [comment]
The schedule is published [here](https://fosdem.org/2016/schedule/track/testing_and_automation/) for what it's worth. I still need to send some more emails out and update the site, then I'll close this issue

**Comment by atodorov** [comment]
This issue is tool old at this point. Closing.
