### ISSUE TITLE
New devroom managers - can we get access here

### ISSUE THREAD

**Issue by atodorov** [fosdem-testingautomation/fosdem-testingautomation.github.io#9]
Hi folks,
I am one of the 4 devroom managers for FOSDEM 2020 (2 merged proposals, 2 contacts in each). 

How can we get write access to this repo?

**Comment by rtyler** [comment]
@atodorov Hey, glad to see that somebody is picking up the Testing and Automation devroom!  I'll get access sorted later tonight after work and let me know if there's anything else I can do to help!

**Comment by atodorov** [comment]
@rtyler the new devroom managers and their backups are:

  * @atodorov - Kiwi TCMS project lead
  * @asankov - Kiwi TCMS developer
  * @roxell - Linaro, QA and Kernel Engineer
  * @metan-ucw - SUSE

**Comment by atodorov** [comment]
I see folks have been invited to this organization so closing this issue.
